[SHRINKRES-320] Resolve control flow issues
shrinkwrap/resolver pull request #184
Opened 2023-11-29 16:21 UTC by petrberan

https://issues.redhat.com/browse/SHRINKRES-320

2023-11-30 07:23 UTC, xstefank requested changes
Fix the parentheses, please

2023-11-30 07:23 UTC, xstefank commented on maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenCoordinateImpl.java
> +        return (packaging.equals(other.packaging));
outer () not needed

2023-11-30 07:23 UTC, xstefank commented on maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenGABaseImpl.java
> +        } else return (groupId.equals(other.groupId));
same

2023-11-30 09:46 UTC, petrberan commented
Fixed everywhere

2024-01-31 09:06 UTC, xstefank approved these changes
LGTM

2024-03-04 12:30 UTC, merged